#!/bin/sh /etc/rc.common

NAME=airplay
START=99

handle_airplay() {
	local config="$1"
	local custom="$2"
	local bname
	local initbuf
	local port
	local password
	local daemonize
	extra="-d"
	
	config_get bname "$1" bname "AirPort"
	config_get initbuf "$1" initbuf "90"
	config_get port "$1" port "5002"
	config_get password "$1" password
	config_get_bool daemonize "$1" daemonize 1
	
	echo "Broadcast to $bname"
	echo "Port $port"
	echo "Password $password"
	
	if [ $daemonize -eq 0 ]
	then
		if [ "x$password" == "x" ]
		then
			shairport -a "$bname" -b $initbuf -o $port 
		else
			shairport -a "$bname" -b $initbuf -o $port -p $password 
		fi	
	fi
	if [ "x$password" == "x" ]
	then
		shairport -a "$bname" -b $initbuf -o $port $extra
	else
		shairport -a "$bname" -b $initbuf -o $port -p $password $extra
	fi
}

start() {
	config_load airplay
	config_foreach handle_airplay airplay
}

stop() {
	killall -9 shairport
	killall -9 avahi-publish-service
}


